#!/bin/bash

chemin=$PWD
installation="/home/jluc/rhizome/mvc"

if (( $1=="cree" ))
then
       case $2 in
        "modele")
		echo "création d'un modele: $chemin/app/modele/modele_$3.rb"
                cp $installation/modeles/modele_debut.rb $chemin/app/modele/modele_$3.rb
                echo 'class $3 < Pattern::Observable' >> $chemin/app/modele/modele_$3.rb
                cp $installation/modeles/modele_fin.rb $chemin/app/modele/modele_$3.rb;;
        "controleur")
		echo "création d'un controleur: $chemin/app/controleur/controleur_$3.rb" 
                cp $installation/modeles/controleur_debut.rb $chemin/app/controleur/controleur_$3.rb
                echo 'class $3' >> $chemin/app/controleur/controleur_$3.rb
                cp $installation/modeles/controleur_fin.rb $chemin/app/controleur/controleur_$3.rb;;

        "action")
		echo "ajout d'une action: $chemin/app/action/action_$3.rb"
                echo 'def $3' >> $chemin/app/action/action_$3.rb
                echo 'end' >> $chemin/app/action/action_$3.rb;;
        "vue")
		echo "création d'une vue: $chemin/app/vue/vue_$3.rb"
                cp $installation/modeles/vue_debut.rb $chemin/app/vue/vue_$3.rb
                echo 'class Vue_$3 < $3' >> $chemin/lib/vue/vue_$3.rb
                cp $installation/modeles/vue_fin.rb $chemin/app/vue/vue_$3.rb;;
        *)
                echo 'erreur de commande';;
        esac

else

	case $1 in
	"init")
		mkdir $2 $2/lib $2/test $2/scripts $2/app $2/modeles $2/app/vue $2/app/controleur $2/app/modele $2/app/action;; 
	*)
		echo 'aide de commande';;

esac
fi

