#!/bin/bash

chemin=$PWD
installation=/home/kantena/rhizome/mvc
action=$1
complement_ou_nom=$2
nom_composant=$3

if  test $action = "cree"
then
    if [ -f .racine ]
        then
            if [ $complement_ou_nom != "modele" ] && [ $complement_ou_nom != "vue" ] && [ $complement_ou_nom != "action" ] && [ $complement_ou_nom != "controleur" ]
                then
                    echo 'erreur de commande'
                else
                    echo "création d'un(e) $complement_ou_nom: $chemin/app/modele/modele_$nom_composant.rb"
                    sed s/"<nom-$complement_ou_nom>"/"$complement_ou_nom_$nom_composant"/g $installation/modeles/$complement_ou_nom.rb >> $chemin/app/$complement_ou_nom/$complement_ou_nom_$nom_composant.rb
                    sed s/"<nom-$complement_ou_nom>"/"$complement_ou_nom_$nom_composant"/g $installation/modeles/test/test_$complement_ou_nom.rb >> $chemin/test/$complement_ou_nom/test_$complement_ou_nom_$nom_composant.rb

               fi
        else
            echo 'vous devez être a la racine de votre projet pour executer cette commande'
        fi

else

    if [ $action = "init" ]
    then
        echo "création de l'arborescence"
        liste="$complement_ou_nom $complement_ou_nom/lib $complement_ou_nom/test $complement_ou_nom/scripts $complement_ou_nom/app $complement_ou_nom/app/vue/jar"
        liste="$liste $complement_ou_nom/app/vue $complement_ou_nom/app/controleur $complement_ou_nom/app/modele $complement_ou_nom/app/action $complement_ou_nom/app/java"
        liste="$liste $complement_ou_nom/test/vue $complement_ou_nom/test/controleur $complement_ou_nom/test/modele $complement_ou_nom/test/action"
        for doss in $liste
        do
            (mkdir $doss && echo Création de $doss) || echo Erreur lors de la création de $doss
        done
        touch .racine
        cd $complement_ou_nom
    elif [ $action = "copie" ] && ( [ $complement_ou_nom = "jar" ] || [ $complement_ou_nom = "java" ] )
    then cp $nom_composant $chemin/app/vue/$complement_ou_nom/
    else
        echo 'aide de commande'
    fi
fi

