package fen;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principale.java
 *
 * Created on 16 juil. 2010, 09:07:58
 */

/**
 *
 * @author kantena
 */
public class Principale extends javax.swing.JFrame {

    /** Creates new form Principale */
    public Principale() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        j_panel_accueil = new javax.swing.JPanel();
        j_menu = new javax.swing.JMenuBar();
        j_menu_applis = new javax.swing.JMenu();
        j_sousmenu_applis = new javax.swing.JMenu();
        j_menitem_quitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout j_panel_accueilLayout = new javax.swing.GroupLayout(j_panel_accueil);
        j_panel_accueil.setLayout(j_panel_accueilLayout);
        j_panel_accueilLayout.setHorizontalGroup(
            j_panel_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        j_panel_accueilLayout.setVerticalGroup(
            j_panel_accueilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 275, Short.MAX_VALUE)
        );

        j_menu_applis.setText("Applis");

        j_sousmenu_applis.setText("Applications");
        j_menu_applis.add(j_sousmenu_applis);

        j_menitem_quitter.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, 0));
        j_menitem_quitter.setText("Quitter");
        j_menitem_quitter.setToolTipText("Quitter l'application rhizome");
        j_menu_applis.add(j_menitem_quitter);

        j_menu.add(j_menu_applis);

        setJMenuBar(j_menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_accueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(j_panel_accueil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem j_menitem_quitter;
    public javax.swing.JMenuBar j_menu;
    public javax.swing.JMenu j_menu_applis;
    public javax.swing.JPanel j_panel_accueil;
    public javax.swing.JMenu j_sousmenu_applis;
    // End of variables declaration//GEN-END:variables

}
